
root: /
baseurl: ""
url: http://www.thinlinevr.com

# Site settings
title: Thin Line
email: syl0113@gmail.com
description: "Thin Line - a perspective taking VR experience."


# Build settings
markdown: kramdown
permalink: pretty
