
root: /
baseurl: ""
url: http://www.thinlinevr.com

# Site settings
title: Thin Line
email: syl0113@gmail.com
description: "Thin Line is a perspective taking VR experience that reveals the internal thoughts and external forces that shape a woman's journey through the healthcare system."

 


# Build settings
markdown: kramdown
permalink: pretty
